version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
