version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ci-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules        # Montaje vacío para evitar conflictos con node_modules del host
    networks:
      - ci-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ci-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ci-network
    depends_on:
      - backend

networks:
  ci-network:
    driver: bridge




